Updates

diff --git a/scripts/gen-shellcomp b/scripts/gen-shellcomp
--- a/scripts/gen-shellcomp
+++ b/scripts/gen-shellcomp
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Create Fish completion script from JSON file
+# Create Bash/Zsh/Fish shell completion script from JSON file
 #
 # Usage: gen-shellcomp {bash|zsh|fish} <command>
 #
@@ -20,6 +20,11 @@ set -o nounset
 set -o pipefail
 if [[ "${TRACE-0}" == "1" ]]; then
     set -o xtrace
+fi
+
+if [[ ! "$(command -v h2o)" ]]; then
+    echo "[error] h2o is missing"
+    exit 1
 fi
 
 basedir="$(dirname "$(readlink -f "$0")")"
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -4,7 +4,8 @@
 #
 #   $ ./run bat
 #
-# Require jq, ajv, parallel
+# Require jq, ajv, parallel, and h2o
+#
 #
 set -o errexit
 set -o nounset
@@ -33,6 +34,11 @@ fi
 if [[ ! "$(command -v ajv)" ]]; then
     echo "[error] ajv is missing. Install ajv-cli via"
     echo "npm install -g ajv-cli"
+    exit 1
+fi
+
+if [[ ! "$(command -v h2o)" ]]; then
+    echo "[error] h2o is missing."
     exit 1
 fi
 
