Add error checking to the tojson script

diff --git a/scripts/tojson b/scripts/tojson
--- a/scripts/tojson
+++ b/scripts/tojson
@@ -20,6 +20,11 @@ if [[ ! "$(command -v jq)" ]]; then
     exit 1
 fi
 
+if [[ ! "$(command -v yq)" ]]; then
+    echo "[error] yq is missing. Install yq to run this script."
+    exit 1
+fi
+
 function scan {
     dir="$1"
     yaml="$basedir/../$dir/yaml/$name.yaml"
